apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: my-first-webserver
  source:
    path: .
    repoURL: https://github.com/thschue/my-team-repo
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
