apiVersion: batch/v1
kind: Job
metadata:
  name: debian-postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: debian-postsync
    spec:
      restartPolicy: Never
      containers:
        - name: debian
          image: debian:bookworm-slim
          command:
            [
              "sh",
              "-c",
              "echo PostSync debian starting...; sleep 20; echo PostSync debian done",
            ]
